# -*- coding: utf-8 -*-
"""README.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CMgBz4gWFJM3ehUPpA5nuyGJDY8mCk09
"""

# SkyHigh Hotels – Hybrid Dynamic Pricing

This Streamlit application implements a hybrid dynamic pricing system using:

- Prophet for demand forecasting
- Machine Learning models for price sensitivity
- Revenue optimization without competitor pricing

## How to Run
pip install -r requirements.txt
streamlit run app.py